### ISSUE TITLE
Fix 12 Maintainability issues in css\style.css

### ISSUE THREAD

**Issue by jd-apprentice** [jd-apprentice/Portfolio#2]
[CodeFactor](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/overview/main) found multiple issues last seen at db483f39e00791063a50c7f8d5f494bd69c627cb:

#### Unexpected duplicate selector &quot;.btn-close&quot;, first used at line 1021 (no-duplicate-selectors)
- [ ]  [css\style.css:1546](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L1546)

#### Unexpected duplicate selector &quot;.modal-content&quot;, first used at line 1075 (no-duplicate-selectors)
- [ ]  [css\style.css:1542](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L1542)

#### Unexpected duplicate selector &quot;.card&quot;, first used at line 942 (no-duplicate-selectors)
- [ ]  [css\style.css:1538](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L1538)

#### Unexpected duplicate selector &quot;.badge&quot;, first used at line 993 (no-duplicate-selectors)
- [ ]  [css\style.css:1534](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L1534)

#### Unexpected duplicate selector &quot;.dropdown-menu&quot;, first used at line 678 (no-duplicate-selectors)
- [ ]  [css\style.css:1524](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L1524)

#### Unexpected duplicate selector &quot;button,
input,
textarea&quot;, first used at line 169 (no-duplicate-selectors)
- [ ]  [css\style.css:1508](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L1508)

#### Unexpected duplicate selector &quot;.btn-lg&quot;, first used at line 644 (no-duplicate-selectors)
- [ ]  [css\style.css:1504](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L1504)

#### Unexpected duplicate selector &quot;.btn&quot;, first used at line 460 (no-duplicate-selectors)
- [ ]  [css\style.css:1499](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L1499)

#### Unexpected duplicate selector &quot;.navbar-brand&quot;, first used at line 826 (no-duplicate-selectors)
- [ ]  [css\style.css:1493](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L1493)

#### Unexpected duplicate selector &quot;.navbar&quot;, first used at line 794 (no-duplicate-selectors)
- [x]  [css\style.css:1482](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L1482)

#### Unexpected duplicate selector &quot;button&quot;, first used at line 161 (no-duplicate-selectors)
- [x]  [css\style.css:178](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L178)

#### Unexpected duplicate selector &quot;ul&quot;, first used at line 119 (no-duplicate-selectors)
- [x]  [css\style.css:124](https://www.codefactor.io/repository/github/jd-apprentice/portfolio/source/main/css/style.css#L124)

**Comment by jd-apprentice** [comment]
Tried fix, seems to work

**Comment by jd-apprentice** [comment]
ul, button, navbar mixed

**Comment by Shubham56-droid** [comment]
I can fix this issue pls assign the issue to me.
